
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.OpenDevicePartnership]
url = "https://raw.githubusercontent.com/OpenDevicePartnership/rust-crate-audits/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.defmt]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.defmt-macros]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.defmt-parser]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.109"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.100"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.64"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.64"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"
